### PR TITLE
Provide auto completion for sparql 1.1 functions

### PR DESCRIPTION
**Pull request by nikolavp**

### CODE REVIEW

**Comment by LaurensRietveld** [comment]
Thanks, good one, I'll incorporate it somewhere next week. I might tweak the get function a bit to see whether we can make this context dependent

**Comment by nikolavp** [comment]
Thanks, I can add the following:
- Need better comment - I just copy pasted the block for variables
- Need context - that's the reason it currently autocompletes on the second character(first implementation was on the first character).
- There is a problem with the tokenization in CM. For example if you have the following

```
select {
....
} where {
...
FILTER(|
}
```

(the cursor is on the open brace) and you ask CM to give you the current token, my expectation was that it would give you a blank token because it should tokenize on **(**, but it doesn't; it returns **FILTER(** and it is then impossible to autocomplete just the function name(because it replaces the whole token after that)

Note that this is work in progress(for example proper comments is a showstopper and I can see that), I just had some time and wantet to share it so there is no double effort.

**Comment by LaurensRietveld** [comment]
Yes, the tokenization is pretty bad when the query is invalid (which is essentially all the time when you're in the middle of writing a query). I wrote a 'getCompleteToken' function to make the token a bit more usable, but perhaps that exact function is the cause of your problem (as it concatenates the string before the cursor until it finds a whitespace). 
This is a tricky problem: simply using the original token function could generate other problems. One example I know of:  a query with a (incomplete) triple pattern such as `<resource> abc|`, would show 'bc' as one token, and 'a' as another (as 'a' is a valid replacement for rdf:type, and occurs in the grammar).

About the context: If I remember correctly, there should be a 'possiblesCurrent' (or something similar) in the token object, containing all the allowed SPARQL terms for the current cursor position.
It might be a bit cluttered (e.g. autocompleting a '<' character in a regular sub pred or obj position does not really benefit the user), but it might provide some nice context. I'm not sure how robust this 'possiblesCurrent' list is when the query is invalid though.. 
However, this list could potentially bypass the token issue you described.

**Comment by LaurensRietveld** [comment]
inactive for too long. feel free to re-open with updates

**Pull request closed without merging**
